# Generated by Django 5.2.3 on 2025-06-25 21:30

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr', 'Dr.'), ('Prof', 'Prof.'), ('Mx', 'Mx.'), ('', '—')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('user_level', models.PositiveSmallIntegerField(default=1)),
                ('permitted_stores', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of permitted stores (any string value)', size=None)),
                ('permitted_licenses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of permitted licenses (any string value)', size=None)),
                ('permitted_brands', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of permitted brands (any string value)', size=None)),
                ('access_profile', models.TextField(blank=True, null=True)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('can_backdate_orders', models.BooleanField(default=False)),
                ('can_login_offline', models.BooleanField(default=False)),
                ('allowed_actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('all_actions_enabled', models.BooleanField(default=False)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('device_key', models.CharField(blank=True, max_length=20, null=True)),
                ('device_label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('activation_token_expires', models.DateTimeField(blank=True, null=True)),
                ('forgot_pin_token', models.UUIDField(blank=True, null=True)),
                ('forgot_pin_token_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='business.business')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
