# Generated by Django 5.2.3 on 2025-06-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_landmark_address_lat_address_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='lng',
            new_name='longitude',
        ),
    ]
