# Generated by Django 5.2.3 on 2025-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_lat_address_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('Manager', 'MANAGER'), ('Cashier', 'CASHIER')], default='Cashier', max_length=50),
        ),
    ]
