# Generated by Django 5.2.3 on 2025-07-06 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_branch_is_default'),
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this user is associated with. Used as part of login credentials.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='business.branch'),
        ),
    ]
