@baseUrl = http://127.0.0.1:8000/api

# =============================
# @name login
# Get JWT token using user_id + password
POST {{baseUrl}}/api/auth/login/
Content-Type: application/json

{
  "user_id": "ITS13CH3U",
  "pin": "6854"
}


###



# =============================
# @name createUser
# Create user with the saved token
POST {{baseUrl}}/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNTI1OTQ1LCJpYXQiOjE3NTEzNTMxNDUsImp0aSI6IjllMDE3NzA2NGYwMzQwODA4NjEzMThhMGY4YmJhMzhkIiwidXNlcl9pZCI6MTV9.5sNz7zHGVFr0-wolgmjkjd7-MuQm1fCtJtb0H7UMODI

{
  "user_id": "USR00223",
  "first_name": "Priya",
  "last_name": "Raman",
  "role": "Manager",
  "permitted_stores": ["ChennaiMain", "PondyBranch"],
  "permitted_licenses": ["MIT", "GPL", "Apache"],
  "permitted_brands": ["Nike", "Adidas", "Puma"],
  "allowed_actions": ["create_order", "refund", "view_report"],
  "all_actions_enabled": false,
  "can_backdate_orders": true,
  "can_login_offline": false,
  "access_profile": null,
  "access_expires_at": null,
  "contact": {
    "email": "malavathvinod470@gmail.com",
    "phone": "+91-9876543210",
    "title": "Ms"
  },
  "address": {
    "address_line1": "123 Gandhi Road",
    "city": "hyderabad",
    "state": "Telangana",
    "zip_code": "500008",
    "country": "IN"
  }
}

###

# =============================
# @name getUserList
# Protected route using same JWT token
GET {{baseUrl}}/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMTIwMjYwLCJpYXQiOjE3NTA5NDc0NjAsImp0aSI6Ijc0ZjQ1YjVjYjQzZDRkMmI4ZTg2OTlkNmM3Y2JkODhkIiwidXNlcl9pZCI6MTR9.fCyimslY3pcGJsm5BAHtnl80IjRMWpMbI0CG2yOACOU

###


### Create a Coupon with Discounts and Customer

POST http://127.0.0.1:8000/api/coupon-campaigns/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNDUzMTkxLCJpYXQiOjE3NTEyODAzOTEsImp0aSI6IjFiOThjY2M5M2I5ODQzODliOWU0Y2VkMTg4NjY3NDQ0IiwidXNlcl9pZCI6MTR9._XOoByNntU5jOvhhAboAcjR7bH7a20oVZUjz0nbwEzY

{
    "couponProvider": "Flipkart",
    "couponCode": "FLIP123",
    "startDate": "2025-07-06",
    "expiryDate": "2025-07-18",
    "campaignName": "Monsoon Sale",
    "discounts": [
        {
            "discountCode": "DISC20"
        },
        {
            "discountCode": "DISC30"
        }
    ],
    "customer": "131122324"
}