# Generated by Django 5.2.3 on 2025-06-28 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_address_landmark_address_lat_address_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid customer ID', regex='^[a-zA-Z0-9_\\-]+$')])),
                ('branch_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_date', models.DateField()),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('addresses', models.ManyToManyField(related_name='customers', to='users.address')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserved_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points_ending_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points_ending_next_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_info', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='customer.customer')),
            ],
        ),
    ]
