# Generated by Django 5.2.3 on 2025-06-28 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('users', '0003_address_landmark_address_lat_address_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='addresses',
        ),
        migrations.AddField(
            model_name='customer',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='users.address'),
        ),
    ]
