# Generated by Django 5.2.3 on 2025-06-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_pan_card_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponProvider', models.CharField(max_length=100)),
                ('couponCode', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('expiryDate', models.DateField()),
                ('campaignName', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='customer.customer')),
                ('discounts', models.ManyToManyField(to='customer.discount')),
            ],
        ),
    ]
