# Generated by Django 5.2.3 on 2025-06-30 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_discount_couponcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_since',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
