# Generated by Django 5.2.3 on 2025-06-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('min', models.PositiveIntegerField(default=0)),
                ('max', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOptionSetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('skuCode', models.CharField(max_length=100)),
                ('isDefault', models.BooleanField(default=False)),
                ('measuringUnit', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max', models.PositiveIntegerField(default=1)),
                ('option_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='inventory.itemoptionset')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=100)),
                ('longName', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skuCode', models.CharField(max_length=100, unique=True)),
                ('barCode', models.CharField(blank=True, max_length=100, null=True)),
                ('groupSKUCode', models.CharField(blank=True, max_length=100, null=True)),
                ('measuringUnit', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('menus', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('priceIncludesTax', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('displayOrder', models.PositiveIntegerField(default=0)),
                ('categoryDisplayOrder', models.PositiveIntegerField(default=0)),
                ('optionSets', models.ManyToManyField(blank=True, to='inventory.itemoptionset')),
                ('variants', models.ManyToManyField(blank=True, to='inventory.itemvariant')),
                ('taxes', models.ManyToManyField(blank=True, to='inventory.tax')),
            ],
        ),
    ]
