# Generated by Django 5.2.3 on 2025-06-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('food', 'Food'), ('health', 'Health'), ('home', 'Home'), ('office', 'Office'), ('restaurant', 'Restaurant'), ('services', 'Services')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
