# Generated by Django 5.2.3 on 2025-07-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_channel_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Indicates if this is the default branch for the business'),
        ),
    ]
