# Generated by Django 5.2.3 on 2025-06-22 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_activation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='activation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
