# Generated by Django 5.2.3 on 2025-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='forgot_pin_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='forgot_pin_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
