# Generated by Django 5.2.3 on 2025-06-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_account_number_business_forgot_pin_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='device_key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
