# Generated by Django 5.2.3 on 2025-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_device_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='device_label',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
