# Generated by Django 5.2.3 on 2025-06-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_business_device_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='device_key_expires',
        ),
    ]
