# Generated by Django 5.2.3 on 2025-06-27 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sku_code', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('supplier_barcodes', models.CharField(blank=True, max_length=255)),
                ('tax_code', models.CharField(blank=True, max_length=100)),
                ('nature_of_item', models.CharField(choices=[('Goods', 'Goods'), ('Service', 'Service')], max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('measuring_unit', models.CharField(blank=True, max_length=20)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('includes_tax', models.BooleanField(default=False)),
                ('allow_price_override', models.BooleanField(default=False)),
                ('allow_discount', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='features.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='features.category')),
                ('charges', models.ManyToManyField(blank=True, to='features.charge')),
                ('tags', models.ManyToManyField(blank=True, to='features.tag')),
            ],
        ),
    ]
