# Generated by Django 5.2.3 on 2025-06-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='allow_discount',
            new_name='not_eligible_for_discount',
        ),
        migrations.AlterField(
            model_name='item',
            name='tax_code',
            field=models.CharField(choices=[('GST', 'GST'), ('CGST', 'CGST'), ('SGST', 'SGST')], default='None', max_length=100),
        ),
    ]
