# Generated by Django 5.2.3 on 2025-06-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_rename_allow_discount_item_not_eligible_for_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='brand',
            new_name='item_brand',
        ),
        migrations.AddField(
            model_name='item',
            name='account',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='optional_set',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='schedules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='taxes',
            field=models.CharField(choices=[('GST', 'GST'), ('CGST', 'CGST'), ('SGST', 'SGST')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='menus',
            field=models.ManyToManyField(to='features.menu'),
        ),
    ]
