# Generated by Django 5.2.3 on 2025-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_menu_rename_image_item_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menus',
        ),
        migrations.AddField(
            model_name='item',
            name='menus',
            field=models.TextField(blank=True),
        ),
    ]
