# Generated by Django 5.2.3 on 2025-06-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_order_amount_paid_order_discount_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_non_chargeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='non_chargeable_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('razorpay', 'Razorpay'), ('non_chargeable', 'Non-Chargeable')], max_length=20, null=True),
        ),
    ]
