# Generated by Django 5.2.3 on 2025-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_order_is_non_chargeable_order_non_chargeable_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='special_notes',
            field=models.TextField(blank=True),
        ),
    ]
